// Copie de lib/catalogues/lyon.ts, faite par scripts/fonction-communaute.mjs : ne pas modifier ici.
import type { Catalogue, Projet } from '../types.ts'

/**
 * Les projets sur la table à Lyon. Coûts en millions d'euros, voyageurs par jour de semaine, durée de chantier en
 * années. Les chiffres viennent des études et délibérations publiques rassemblées pour la première version du
 * simulateur ; leurs tracés sont dans data/projets.
 */
const projets: Projet[] = [
  {
    id: 'grande-dorsale',
    feminin: true,
    nom: 'Grande Dorsale est-ouest',
    genre: 'Nouvelle ligne de métro',
    description: '',
    mode: 'metro',
    cout: 6000,
    voyageurs: 182000,
    duree: 30,
    trace: 'grande-dorsale',
  },
  {
    id: 'metro-e-bellecour',
    nom: 'Métro E jusqu’à Bellecour',
    genre: 'Nouvelle ligne de métro',
    description: '',
    mode: 'metro',
    cout: 1800,
    voyageurs: 64000,
    duree: 14,
    trace: 'metro-e-bellecour',
  },
  {
    id: 'ext-a-est',
    feminin: true,
    nom: 'Extension de la ligne A à l’est',
    genre: 'Prolongement de métro',
    description: '',
    mode: 'metro',
    cout: 2000,
    voyageurs: 48500,
    duree: 8,
    trace: 'ext-a-est',
  },
  {
    id: 'ext-d',
    feminin: true,
    nom: 'Extension de la ligne D',
    genre: 'Prolongement de métro',
    description: '',
    mode: 'metro',
    cout: 1400,
    voyageurs: 40000,
    duree: 7,
    trace: 'ext-d',
  },
  {
    id: 'metro-e-part-dieu',
    nom: 'Métro E jusqu’à Part-Dieu',
    genre: 'Prolongement de métro',
    description: '',
    mode: 'metro',
    cout: 600,
    voyageurs: 38000,
    duree: 4,
    requiert: 'metro-e-bellecour',
    trace: 'metro-e-part-dieu',
  },
  {
    id: 'ligne-du-nord',
    feminin: true,
    nom: 'Ligne du Nord',
    genre: 'Nouvelle ligne vers Rillieux-la-Pape',
    description: '',
    mode: 'tram',
    cout: 350,
    voyageurs: 40000,
    duree: 8,
    trace: 'ext-b-nord',
    variantes: [
      {
        id: 'tram-surface',
        nom: 'Tramway en surface',
        detail: 'Le tracé reste en surface, le chantier est plus court.',
        mode: 'tram',
        cout: 350,
        voyageurs: 40000,
        duree: 8,
      },
      {
        id: 'tram-enterre',
        nom: 'Tramway enterré',
        detail: 'Plus régulier, mais la rue au-dessus n’est pas réaménagée.',
        mode: 'tram',
        cout: 900,
        voyageurs: 55000,
        duree: 14,
      },
      {
        id: 'metro',
        nom: 'Métro, prolongement de la ligne B',
        detail: 'Depuis Charpennes, en souterrain.',
        mode: 'metro',
        cout: 3300,
        voyageurs: 71500,
        duree: 15,
      },
    ],
  },
  {
    id: 'teol',
    nom: 'Tramway express de l’ouest lyonnais',
    genre: 'Nouveau tramway',
    description: '',
    mode: 'tram',
    cout: 800,
    voyageurs: 55000,
    duree: 6,
    trace: 'teol',
    option: {
      nom: 'Enterrer tout le tracé',
      detail:
        'Le tramway passe en souterrain partout. La régularité s’améliore, mais la rue n’est pas réaménagée et le chantier dure deux ans de plus.',
      surcout: 300,
      duree: 8,
    },
  },
  {
    id: 'modern-a',
    action: 'moderniser',
    feminin: true,
    nom: 'Modernisation de la ligne A',
    genre: 'Rénovation d’une ligne de métro',
    description: '',
    mode: 'renovation',
    cout: 686,
    voyageurs: 312000,
    duree: 9,
    trace: 'modern-a',
  },
  {
    id: 'modern-d',
    action: 'moderniser',
    feminin: true,
    nom: 'Modernisation de la ligne D',
    genre: 'Rénovation d’une ligne de métro',
    description: '',
    mode: 'renovation',
    // Délibération 25-079 de Sytral Mobilités, autorisations de programme 2026 : programme « Avenir métro D »,
    // 339,1 M€ avant actualisation, 522,4 M€ après.
    cout: 522,
    voyageurs: 220500,
    duree: 4,
    trace: 'modern-d',
  },
  {
    id: 'modern-c',
    action: 'moderniser',
    feminin: true,
    nom: 'Modernisation de la ligne C',
    genre: 'Rénovation d’une ligne de métro',
    description: '',
    mode: 'renovation',
    cout: 239,
    voyageurs: 28000,
    duree: 9,
    trace: 'modern-c',
  },
  {
    id: 't12-c3',
    nom: 'Tram du Centre',
    genre: 'Nouveau tramway',
    description: '',
    mode: 'tram',
    cout: 540,
    voyageurs: 75000,
    duree: 6,
    trace: 't12-c3',
  },
  {
    id: 'ligne-ouest',
    feminin: true,
    nom: 'Ligne de l’Ouest',
    genre: 'Nouvelle ligne dans l’ouest lyonnais',
    description: '',
    mode: 'bus',
    cout: 240,
    voyageurs: 20000,
    duree: 6,
    trace: 'ligne-ouest',
    variantes: [
      {
        id: 'bhns',
        nom: 'Bus à haut niveau de service',
        detail: 'Des voies réservées et des stations aménagées, sans rails.',
        mode: 'bus',
        cout: 240,
        voyageurs: 20000,
        duree: 6,
      },
      {
        id: 'tram',
        nom: 'Tramway',
        detail: 'Plus de places à bord, pour un chantier plus long et plus cher.',
        mode: 'tram',
        cout: 600,
        voyageurs: 25000,
        duree: 8,
      },
    ],
  },
  {
    id: 'teol-craponne',
    nom: 'Tramway de l’ouest jusqu’à Craponne',
    genre: 'Prolongement de tramway',
    description: '',
    mode: 'tram',
    cout: 300,
    voyageurs: 25000,
    duree: 5,
    requiert: 'teol',
    trace: 'teol-craponne',
  },
  {
    id: 't8',
    nom: 'Tramway T8',
    genre: 'Nouveau tramway',
    description: '',
    mode: 'tram',
    cout: 245,
    voyageurs: 30000,
    duree: 4,
    trace: 't8',
  },
  {
    id: 'telepherique-ouest',
    nom: 'Téléphérique de l’Ouest',
    genre: 'Téléphérique urbain',
    description: '',
    mode: 'cable',
    cout: 200,
    voyageurs: 18000,
    duree: 5,
    trace: 'telepherique-ouest',
  },
  {
    id: 'bhns-rive-droite',
    feminin: true,
    nom: 'Ligne du Rhône rive droite',
    genre: 'Nouvelle ligne le long du Rhône',
    description: '',
    mode: 'bus',
    cout: 50,
    voyageurs: 20000,
    duree: 3,
    trace: 'bhns-rive-droite',
    variantes: [
      {
        id: 'bhns',
        nom: 'Bus à haut niveau de service',
        detail: 'Des voies réservées sur les rues existantes, pour un investissement minime.',
        mode: 'bus',
        cout: 50,
        voyageurs: 20000,
        duree: 3,
      },
      {
        id: 'tram',
        nom: 'Tramway',
        detail: 'Plus de places et plus de confort, pour trois fois le prix.',
        mode: 'tram',
        cout: 165,
        voyageurs: 25000,
        duree: 3,
      },
    ],
  },
  {
    id: 'bhns-parilly',
    nom: 'Bus rapide de Parilly',
    genre: 'Bus à haut niveau de service',
    description: '',
    mode: 'bus',
    cout: 80,
    voyageurs: 25000,
    duree: 3,
    trace: 'bhns-parilly',
  },
  {
    id: 't9-final',
    action: 'achever',
    nom: 'Achèvement du T9',
    genre: 'Fin de chantier d’un tramway',
    description: '',
    mode: 'tram',
    cout: 75,
    voyageurs: 38000,
    duree: 1,
    trace: 't9-final',
  },
  {
    id: 't10-final',
    action: 'achever',
    nom: 'Achèvement du T10',
    genre: 'Fin de chantier d’un tramway',
    description: '',
    mode: 'tram',
    cout: 75,
    voyageurs: 42000,
    duree: 1,
    trace: 't10-final',
  },
  {
    id: 'navette-fluv',
    feminin: true,
    nom: 'Navette fluviale',
    genre: 'Transport par bateau',
    description: '',
    mode: 'fluvial',
    cout: 40,
    voyageurs: 1500,
    duree: 4,
    trace: 'navette-fluv',
  },
  {
    id: 't3-renf',
    action: 'renforcer',
    nom: 'T3 en express',
    genre: 'Renfort d’un tramway',
    description: '',
    mode: 'tram',
    cout: 35,
    voyageurs: 12000,
    duree: 2,
    trace: 't3-renf',
  },
  {
    id: 'bhns-kimmerling',
    action: 'achever',
    nom: 'Achèvement du bus Part-Dieu',
    genre: 'Fin de chantier d’un bus rapide',
    description: '',
    mode: 'bus',
    cout: 30,
    voyageurs: 8000,
    duree: 1,
    trace: 'bhns-kimmerling',
  },
  {
    id: 'electrification-bus',
    action: 'electrifier',
    feminin: true,
    nom: 'Électrification des bus',
    genre: 'Parc de bus',
    description: '',
    mode: 'bus',
    cout: 460,
    voyageurs: 0,
    duree: 6,
  },
]

export const lyon: Catalogue = {
  projets,
  tutoriel: {
    projet: 't8',
    consigne: 'Touchez le tramway T8, en noir sur la carte.',
    detail: 'Chaque pointillé est un projet réel, avec son prix écrit dessus. Le T8 relierait Vaulx-en-Velin à Vénissieux pour 245 M€.',
  },
}
